### ISSUE TITLE
Crash on boot -- NullPointerException

### ISSUE THREAD

**Issue by GrahamBlanshard** [GrahamBlanshard/WiseRadar#3]
Hold device in Landscape, boot app, it should launch with img as default android icon. Upon refresh it will instantly crash.

I *believe* the problem is handling Layout switching prior to the fragment being prepared to handle it itself.

-Look back into old code, prior to Fragment update to see how Activity layout handling was taken care of.

**Comment by GrahamBlanshard** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'void wiseguys.radar.ui.RadarFragment.refresh()' on a null object reference
	at wiseguys.radar.ui.MainActivity.onOptionsItemSelected(MainActivity.java:58)
	at android.app.Activity.onMenuItemSelected(Activity.java:2885)
	at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1133)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:186)
	at android.widget.AdapterView.performItemClick(AdapterView.java:305)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1146)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3053)
	at android.widget.AbsListView$3.run(AbsListView.java:3860)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by GrahamBlanshard** [comment]
Well that's dumb. The landscape layout wasn't updated when I switched to fragments. Fixed in 2.4
