### ISSUE TITLE
Crash on Refresh

### ISSUE THREAD

**Issue by GrahamBlanshard** [GrahamBlanshard/WiseRadar#4]
Somehow radarFragment is null when selecting menu refresh option.

I should check for existance of the object, possibly lost since I don't maintain an "onResume" function in the activity.

**Comment by GrahamBlanshard** [comment]
Also this:

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.TextView.setText(java.lang.CharSequence)' on a null object reference
	at wiseguys.radar.ui.RadarFragment.refresh(RadarFragment.java:131)
	at wiseguys.radar.ui.MainActivity.onOptionsItemSelected(MainActivity.java:58)
	at android.app.Activity.onMenuItemSelected(Activity.java:2998)
	at com.android.internal.policy.impl.PhoneWindow.onMenuItemSelected(PhoneWindow.java:1199)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:155)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894)
	at com.android.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:222)
	at android.widget.AdapterView.performItemClick(AdapterView.java:334)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1544)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3686)
	at android.widget.AbsListView$3.run(AbsListView.java:5602)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:5835)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)


Seems we lose a text fragment somehow? Might be related.

**Comment by GrahamBlanshard** [comment]
Same issue as last one, closing after testing, will fix... soon
